#!/usr/bin/env python3
import asyncio
from argparse import ArgumentParser
from flickrdump import flickrdump

def parse_args():
    parser = ArgumentParser(description='Flickr Dump')
    parser.add_argument('-A', '--api-key', required=True,
                        help='An API-key for accessing the Flickr API.')
    parser.add_argument('-S', '--api-secret', required=True,
                        help='An API-secret for accessing the Flickr API.')
    parser.add_argument('-U', '--user-id', required=True,
                        help='Your Flickr UserID, Can be found at http://idgettr.com/')
    parser.add_argument('-P', '--path', default='./data',
                        help='The target path to download photos')
    return parser.parse_args()

def main():
    """
    Flickr-Dump CLI function.
    """
    args = parse_args()
    # Run the async dump function using asyncio.run
    return asyncio.run(flickrdump.dump(args.api_key, args.api_secret, args.user_id, args.path))

if __name__ == '__main__':
    exit(main())
